name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        run: dotnet restore portfolio-analytics-backend.sln

      - name: Build (Release)
        run: dotnet build portfolio-analytics-backend.sln --configuration Release --no-restore
        
      - name: Test (Release)
        run: dotnet test portfolio-analytics-backend.sln --configuration Release --no-build
